[package]
name = "pi_serv"
version = "0.1.0"
authors = [""]

[dependencies]
fnv = "*"
clap = "2.31.2"
toml = "0.4.6"
pi_lib = { path = "../pi_lib" }
pi_db = { path = "../pi_db" }
pi_vm = { path = "../pi_vm" }
net = { path = "../pi_net/net" }
mqtt = { path = "../pi_net/mqtt" }
rpc = { path = "../pi_net/rpc" }