[package]
name = "pi_serv"
version = "0.1.0"
authors = [""]

[dependencies]
clap = "2.31.2"
toml = "0.4.6"
json = "0.11.13" 
pi_lib = { path = "../pi_lib" }
pi_vm = { path = "../pi_vm" }
lazy_static = "*"
pi_test = { path = "../pi_test" }
pi_math = { path = "../pi_math" }
pi_crypto = { path = "../pi_crypto" }